#define INTEGER
#define DOUBLE
#define POPEN
#define PCLOSE
#define ARROPEN
#define ARRCLOSE
#define CUROPEN
#define CURCLOSE
#define PLUS
#define MULTIPLY
#define MINUS
#define DIVIDE
#define MOD
#define PLUSPLUS
#define MINUSMINUS
#define POW
#define EQUAL
#define COMMA
#define PLUSEQUAL
#define MINUSEQUAL
#define MULTIPLYEQUAL
#define DIVIDEEQUAL
#define ISEQUAL
#define NOTEQUAL
#define GANDE
#define LANDE
#define GREATER
#define LESS
#define OR
#define AND
#define IF
#define ELSE
#define FUNC
#define LOOP
#define PRINT
#define INPUT
#define PRIMITIVETYPES
#define BOOL
#define IDENTIFIER
#define STRING